version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  backend:
    build: .
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://admin:password@mongodb:27017/ICT_E_learning
    depends_on:
      - mongodb

volumes:
  mongodb_data:
